export const FETCH_POKEMONS = 'FETCH_POKEMONS';
export const SET_CARD_ID = 'SET_CARD_ID';
export const SET_NEXT_PAGE_URL = 'SET_NEXT_PAGE_URL';
export const TOGGLE_FETCHING = 'TOGGLE_FETCHING';
export const CATCH_POKEMON = 'CATCH_POKEMON';
export const RELEASE_POKEMON = 'RELEASE_POKEMON';